services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
    volumes:
      - wp_html:/var/www/html
      - ./wp-content/themes/cic-theme:/var/www/html/wp-content/themes/cic-theme
    depends_on:
      - db
      - redis

  wp-cli:
    image: wordpress:cli
    user: "33:33"
    depends_on:
      - db
      - wordpress
    volumes:
      - wp_html:/var/www/html
      - ./wp-content/themes/cic-theme:/var/www/html/wp-content/themes/cic-theme
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    command: >
      sh -c "
      echo 'Waiting for WordPress and DB to be ready...';
      sleep 20;
      wp core install --url=http://localhost:8000 --title='GS Sanyal School of Technology' --admin_user=admin --admin_password=admin --admin_email=admin@example.com --path=/var/www/html;
      wp theme activate cic-theme --path=/var/www/html;
      wp plugin install redis-cache --activate --path=/var/www/html;
      wp redis enable --path=/var/www/html;
      echo 'WordPress Setup Complete!';
      "

volumes:
  db_data:
  wp_html:

